version: "3.9"

services:
  postgresql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    shm_size: 256M

  # proxy-api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     target: dev
  #     args:
  #       ENVIRONMENT: development
  #   env_file:
  #     - .env
  #   environment:
  #     - REDIS_URL=redis://sproxy-redis:6379
  #     - POSTGRES_HOST=sproxy-postgresql
  #   depends_on:
  #     sproxy-postgresql:
  #       condition: service_healthy
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/var/task:cached
  #     - .cache:/tmp/pip/cache:cached
  #   networks:
  #     - sproxy-net

volumes:
  db-data:
