# Default values for url-shortener.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/kayleevo9x/playground/url-shortener-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"

resources: 
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

envVars:
  POSTGRES_HOST: postgresql.postgresql.svc.cluster.local
  LOG_LEVEL: INFO

serviceAccount: 
  create: True