services:
  app:
    build:
      context: ..
      dockerfile: url-shortener/Dockerfile
    env_file: devcontainer.env
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached
      
    command: sleep infinity 
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: host
