global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
      
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'loki'
    dns_sd_configs:
      - names:
          - loki-read
          - loki-write
        type: A
        port: 3100
  - job_name: 'promtail'
    dns_sd_configs:
      - names:
          - promtail
        type: A
        port: 9080
  - job_name: 'app_metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:8000'
          # celery exporter
          # - 'host.docker.internal:9808'
          # query exporter
          # - 'host.docker.internal:9534'