x-environment:
    &default-environment
    POSTGRES_USER: local
    POSTGRES_PASSWORD: local
    POSTGRES_DB: app
    POSTGRES_HOST: postgres

services:
  postgres:
    image: postgres:16-alpine
    environment: *default-environment
    ports:
      - "5432:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    environment: *default-environment
    container_name: api-test
    volumes:
      - ./output/:/app/output
    depends_on:
      postgres:
        condition: service_healthy