services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    environment:
      - POSTGRES_HOST=host.docker.internal
    container_name: api-test
    volumes:
      - ./output/:/app/output