apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urlshortener
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: urlshortener
    server: {{ .Values.spec.destination.server }}
  project: argocd-app-of-apps
  source:
    path: argocd-apps/url-shortener
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
