apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: postgresql
    server: {{ .Values.spec.destination.server }}
  project: argocd-app-of-apps
  source:
    path: argocd-apps/helm-postgresql
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
