apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urlshortener
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: urlshortener
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # Automatic sync will not delete resources if false
      selfHeal: true # Automatic sync to roll back manual changes done on cluster
    syncOptions:
      - CreateNamespace=true
  project: argocd-app-of-apps
  source:
    path: argocd-apps/url-shortener
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
