name: Python API CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'applications/url-shortener/url-shortener/**'
      - 'applications/url-shortener/pyproject.toml'
permissions:
  contents: write
  checks: write
  pull-requests: write
  
env:
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.8.3"

jobs:
  lint:
    permissions: 
      contents: read
      checks: write
    runs-on: ubuntu-latest
    name: Linter
    defaults:
      run:
        working-directory: applications/url-shortener

    steps:
    - uses: actions/checkout@v4
    - name: Run Linter  
      uses: reviewdog/action-flake8@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        flake8_args: "--count --show-source --statistics --max-line-length=160"
        fail_on_error: true

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: applications/url-shortener
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Test with pytest
      run: |
        docker compose -f docker-compose-test.yml up --build --abort-on-container-exit

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: applications/url-shortener/output/pytest-coverage.xml
        junitxml-path: applications/url-shortener/output/test-results.xml
        junitxml-title: Test Summary
        remove-link-from-badge: true