name: Python API CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'url-shortener/**'
      - '!url-shortener/**.md'

env:
  POSTGRES_USER: local
  POSTGRES_PASSWORD: local
  POSTGRES_DB: app
  POSTGRES_PORT: 5432
  POSTGRES_HOST: localhost
  PYTHON_VERSION: "3.12"
  POETRY_VERSION: "1.8.3"

jobs:
  lint:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    name: Linter
    defaults:
      run:
        working-directory: url-shortener

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Lint with flake8 for syntax errors or undefined names
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run linter and comment PR
      uses: matias-martini/flake8-pr-comments-action@main
      with:
        github_token: ${{ github.token }}
        cfg_path: .flake8

  # TODO
  # test: